### ISSUE TITLE
Reseting earns cupcakes from 0 smiles

### ISSUE THREAD

**Issue by loudaslife** [blackhole12/PonyClicker#78]
I reset my game and have 100,000+ cupcakes. I now have a completely new session, with 0 smiles and 0 buildings (apart from the first pony).

If I immediately reset again, having made no progress, I earn 45 cupcakes. The game claims that these cupcakes come from 14 nonillion smiles, which I don't have.

(This is on v1.0.1)

EDIT: Just noticed that the All Time Smile count also increases

![bc5355ea32](https://cloud.githubusercontent.com/assets/7320392/7875818/c6132b82-0587-11e5-8519-5f95c114c383.jpg)
![66d5feb9ea](https://cloud.githubusercontent.com/assets/7320392/7875819/c79ea814-0587-11e5-9309-7da9983b916a.png)

**Comment by blackhole12** [comment]
I am unable to recreate this. Furthermore, there is no version v1.0.1 except in the beta branch. This WAS a bug caused by pinkie clones not being deleted, but it was fixed before I pushed to gh-pages. Are you sure you aren't in the beta branch? Have you refreshed the window? I can push to beta branch again, which will fix this bug (because it was already fixed in master), but I want to verify that you are actually in /beta/ and not in the official release.

**Comment by loudaslife** [comment]
This is weird.

Okay, I opened both the regular branch and the beta, and did a full refresh on both to make sure there's no weird caching stuff. Also did a FULL wipe of save data on both.

The version numbers are as expected, regular branch is v1.0 and beta is v1.0.1

Then, I imported [this save.](http://pastebin.com/NV9jHy6t)

By resetting multiple times, I can reliably cause the "reset cupcake glitch" in the BETA v1.0.1 branch, but NOT in the regular v1.0 branch. WTF?

I also have the screenshots in my earlier comment showing the glitch happening in what APPEARS to be regular branch, but who even knows. I could've sworn the version number that I saw originally when taking those screenshots was 1.0.1, though I can't say that with complete confidence.

Have some screenshots as proof I'm not completely crazy.

![6dfbb742ff](https://cloud.githubusercontent.com/assets/7320392/7877102/18a848ba-059b-11e5-90af-a9d50e8df2b9.png)
![8e5544303f](https://cloud.githubusercontent.com/assets/7320392/7877104/1ce3e2c2-059b-11e5-8d00-0a1e21d80064.png)

**Comment by blackhole12** [comment]
Well that's expected, because Beta is at v1.0.1 (this was to test the revision update working properly), which is actually further behind than the main branch. I'm closing this as no repro since it was technically already fixed.

**Comment by 3plus4i** [comment]
Returning to PonyClicker after two years I noticed that this issue is still (or again?) valid with the current version (v1.0.7 from the gh-pages).
![scr43](https://cloud.githubusercontent.com/assets/12765347/26760342/bc54f1c4-4915-11e7-970a-ff6b5ffa83ae.png)
I started a complete new game in a private window of Firefox and immediately reseted it. I get 1 cupcake, no matter if I reset with 1 or zero total smiles. I just did it with 1 smile for the screenshot so the line for smiles all time does show. I'm going to take a look at the code, I wanted to know how the function works and how much smiles you need for a specific amount of smiles anyway.
